name: CI Pipeline on Validation 

on:
    push:
        branches:
          - main

jobs:
  test-and-package:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Waiting for integration test
        uses: lewagon/wait-on-check-action@v1.3.1
        with: 
          ref: ${{ github.ref }}
          check-name: 'Checking Integration Test'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          running-workflow-name: ./.github/workflows/healthCheck.yaml
          wait-interval: 10
          allowed-conclusions: success

      - name: Set .env file
        run: |
         touch .env
         echo DATABASE_PASSWORD = ${{ secrets.DATABASE_PASSWORD }} >> .env
         echo DATABASE_NAME = ${{ secrets.DATABASE_NAME }} >> .env
         echo DATABASE_USER = ${{ secrets.DATABASE_USER }} >> .env
         echo PORT = ${{ secrets.PORT }} >> .env
         echo HOSTNAME = ${{ secrets.HOSTNAME }} >> .env
         echo DEFAULTUSERPATH = ${{ secrets.DEFAULTUSERPATH }} >> .env

      - name: Create user.csv
        run: |
         touch users.csv
         echo "${{ secrets.USERS_CSV }}" >> users.csv
          
      - name: Build application artifact
        run: zip -r webapp.zip .
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Initialize packer configuration
        run: |
            cd packer
            packer init appconfig.pkr.hcl
        
      - name: Build AMI with Packer
        run: |
            cd packer 
            packer build appconfig.pkr.hcl
