name: Healthz CI
on: [push]

jobs:
  Run-Integration-test-for-healthz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up MariaDB
        run: |
          sudo apt-get update
          sudo apt-get install mariadb-server -y
          sudo systemctl start mariadb
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'manav1201'; flush privileges;"

      - name: Use Node.js 18v
        uses: actions/setup-node@v3
        with:
            node-version: 18.x
            cache: 'npm'

      - name: Set .env file
        run: |
          touch .env
          echo DATABASE_PASSWORD = manav1201 >> .env
          echo DATABASE_NAME = cloud_01 >> .env
          echo DATABASE_USER = root >> .env
          echo PORT = 3306 >> .env
          echo HOSTNAME = 127.0.0.1 >> .env
          echo DEFAULTUSERPATH = "" >> .env

      - name: Run Integration Test
        run: |
            ls -A
            npm i -force
            npm test